[[new-features]]
= New & Noteworthy

[[new-features.1-2-0]]
== What's New in Spring Data R2DBC 1.2.0

* Deprecate Spring Data R2DBC `DatabaseClient` and move off deprecated API in favor of Spring R2DBC. Consult the <<upgrading.1.1-1.2,Migration Guide>> for further details.
* Support for <<entity-callbacks>>.
* <<r2dbc.auditing,Auditing>> through `@EnableR2dbcAuditing`.

[[new-features.1-1-0]]
== What's New in Spring Data R2DBC 1.1.0

* Introduction of `R2dbcEntityTemplate` for entity-oriented operations.
* <<r2dbc.repositories.queries,Query derivation>>.
* Support interface projections with `DatabaseClient.as(…)`.
* <<r2dbc.datbaseclient.filter,Support for `ExecuteFunction` and `StatementFilterFunction` via `DatabaseClient.filter(…)`>>.

[[new-features.1-0-0]]
== What's New in Spring Data R2DBC 1.0.0

* Upgrade to R2DBC 0.8.0.RELEASE.
* `@Modifying` annotation for query methods to consume affected row count.
* Repository `save(…)` with an associated Id terminates with `TransientDataAccessException` if the row does not exist in the database.
* Added `SingleConnectionConnectionFactory` for testing using connection singletons.
* Support for {spring-framework-ref}/core.html#expressions[SpEL expressions] in `@Query`.
* `ConnectionFactory` routing through `AbstractRoutingConnectionFactory`.
* Utilities for schema initialization through `ResourceDatabasePopulator` and `ScriptUtils`.
* Propagation and reset of Auto-Commit and Isolation Level control through `TransactionDefinition`.
* Support for Entity-level converters.
* Kotlin extensions for reified generics and <<kotlin.coroutines,Coroutines>>.
* Add pluggable mechanism to register dialects.
* Support for named parameters.
* Initial R2DBC support through `DatabaseClient`.
* Initial Transaction support through `TransactionalDatabaseClient`.
* Initial R2DBC Repository Support through `R2dbcRepository`.
* Initial Dialect support for Postgres and Microsoft SQL Server.
