DROP TABLE MANUAL/
DROP TABLE LEGO_SET/

DROP SEQUENCE LEGO_SET_SEQ/
DROP SEQUENCE MANUAL_SEQ/

CREATE TABLE LEGO_SET ( ID1 NUMBER(13,0), "NAME" VARCHAR2(30))/
CREATE TABLE MANUAL ( ID2 NUMBER(13,0), LEGO_SET NUMBER(13,0), ALTERNATIVE NUMBER(13,0), CONTENT VARCHAR2(2000))/

CREATE SEQUENCE LEGO_SET_SEQ/
CREATE SEQUENCE MANUAL_SEQ/

CREATE OR REPLACE TRIGGER LEGO_SET_ON_INSERT
BEFORE INSERT ON LEGO_SET
  FOR EACH ROW
BEGIN
  SELECT LEGO_SET_SEQ.nextval
  INTO :new.id1
  FROM dual;
END;/

CREATE OR REPLACE TRIGGER MANUAL_ON_INSERT
  BEFORE INSERT ON MANUAL
  FOR EACH ROW
BEGIN
  SELECT MANUAL_SEQ.nextval
  INTO :new.id2
  FROM dual;
END;/

ALTER TABLE LEGO_SET
  ADD (
    CONSTRAINT LEGO_SET_PK PRIMARY KEY (id1)
  )/

ALTER TABLE MANUAL
  ADD (
    CONSTRAINT MANUAL_PK PRIMARY KEY (id2)
  )/

ALTER TABLE MANUAL ADD FOREIGN KEY (LEGO_SET)
REFERENCES LEGO_SET(id1)/


DROP TABLE ONE_TO_ONE_PARENT/
DROP TABLE Child_No_Id/
DROP TABLE LIST_PARENT/
DROP TABLE element_no_id/

DROP SEQUENCE ONE_TO_ONE_PARENT_SEQ/
DROP SEQUENCE LIST_PARENT_SEQ/

CREATE TABLE ONE_TO_ONE_PARENT ( id3 NUMBER(13,0), content VARCHAR2(30))/
CREATE TABLE Child_No_Id (ONE_TO_ONE_PARENT NUMBER(13,0), content VARCHAR2(30))/

CREATE TABLE LIST_PARENT ( id4 NUMBER(13,0), NAME VARCHAR2(100))/
CREATE TABLE element_no_id ( content VARCHAR2(100), LIST_PARENT_key NUMBER(13,0), LIST_PARENT NUMBER(13,0))/

ALTER TABLE ONE_TO_ONE_PARENT
  ADD (
    CONSTRAINT ONE_TO_ONE_PARENT_PK PRIMARY KEY (id3)
  )/

ALTER TABLE Child_No_Id
  ADD (
    CONSTRAINT Child_No_Id PRIMARY KEY (ONE_TO_ONE_PARENT)
  )/

ALTER TABLE LIST_PARENT
  ADD (
    CONSTRAINT LIST_PARENT_PK PRIMARY KEY (id4)
  )/

CREATE SEQUENCE ONE_TO_ONE_PARENT_SEQ/
CREATE SEQUENCE LIST_PARENT_SEQ/

CREATE OR REPLACE TRIGGER ONE_TO_ONE_PARENT_ON_INSERT
BEFORE INSERT ON ONE_TO_ONE_PARENT
  FOR EACH ROW
BEGIN
  SELECT ONE_TO_ONE_PARENT_SEQ.nextval
  INTO :new.id3
  FROM dual;
END;/

CREATE OR REPLACE TRIGGER LIST_PARENT_ON_INSERT
  BEFORE INSERT ON LIST_PARENT
  FOR EACH ROW
BEGIN
  SELECT LIST_PARENT_SEQ.nextval
  INTO :new.id4
  FROM dual;
END;/
