CREATE TABLE LEGO_SET
(
  id1  BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(30)
);
CREATE TABLE MANUAL
(
  id2         BIGINT AUTO_INCREMENT PRIMARY KEY,
  LEGO_SET    BIGINT,
  ALTERNATIVE BIGINT,
  CONTENT     VARCHAR(2000)
);

ALTER TABLE MANUAL
  ADD FOREIGN KEY (LEGO_SET)
    REFERENCES LEGO_SET (id1);

CREATE TABLE ONE_TO_ONE_PARENT
(
  id3     BIGINT AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(30)
);
CREATE TABLE Child_No_Id
(
  ONE_TO_ONE_PARENT INTEGER PRIMARY KEY,
  content           VARCHAR(30)
);

CREATE TABLE LIST_PARENT
(
  id4  BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100)
);
CREATE TABLE element_no_id
(
  content         VARCHAR(100),
  LIST_PARENT_key BIGINT,
  LIST_PARENT     BIGINT
);

CREATE TABLE BYTE_ARRAY_OWNER
(
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
  BINARY_DATA VARBINARY(20) NOT NULL
);

CREATE TABLE CHAIN4
(
  FOUR       BIGINT AUTO_INCREMENT PRIMARY KEY,
  FOUR_VALUE VARCHAR(20)
);


CREATE TABLE CHAIN3
(
  THREE       BIGINT AUTO_INCREMENT PRIMARY KEY,
  THREE_VALUE VARCHAR(20),
  CHAIN4      BIGINT,
  FOREIGN KEY (CHAIN4) REFERENCES CHAIN4(FOUR)
);

CREATE TABLE CHAIN2
(
  TWO       BIGINT AUTO_INCREMENT PRIMARY KEY,
  TWO_VALUE VARCHAR(20),
  CHAIN3      BIGINT,
  FOREIGN KEY (CHAIN3) REFERENCES CHAIN3(THREE)
);

CREATE TABLE CHAIN1
(
  ONE       BIGINT AUTO_INCREMENT PRIMARY KEY,
  ONE_VALUE VARCHAR(20),
  CHAIN2      BIGINT,
  FOREIGN KEY (CHAIN2) REFERENCES CHAIN2(TWO)
);

CREATE TABLE CHAIN0
(
  ZERO       BIGINT AUTO_INCREMENT PRIMARY KEY,
  ZERO_VALUE VARCHAR(20),
  CHAIN1      BIGINT,
  FOREIGN KEY (CHAIN1) REFERENCES CHAIN1(ONE)
);