DROP TABLE IF EXISTS MANUAL;
DROP TABLE IF EXISTS LEGO_SET;
CREATE TABLE LEGO_SET
(
  id1  BIGINT IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
);
CREATE TABLE MANUAL
(
  id2         BIGINT IDENTITY PRIMARY KEY,
  LEGO_SET    BIGINT,
  ALTERNATIVE BIGINT,
  CONTENT     VARCHAR(2000)
);
ALTER TABLE MANUAL
  ADD FOREIGN KEY (LEGO_SET) REFERENCES LEGO_SET (id1);

DROP TABLE IF EXISTS Child_No_Id;
DROP TABLE IF EXISTS ONE_TO_ONE_PARENT;
CREATE TABLE ONE_TO_ONE_PARENT
(
  id3     BIGINT IDENTITY PRIMARY KEY,
  content VARCHAR(30)
);
CREATE TABLE Child_No_Id
(
  ONE_TO_ONE_PARENT BIGINT PRIMARY KEY,
  content           VARCHAR(30)
);

DROP TABLE IF EXISTS element_no_id;
DROP TABLE IF EXISTS LIST_PARENT;
CREATE TABLE LIST_PARENT
(
  id4  BIGINT IDENTITY PRIMARY KEY,
  NAME VARCHAR(100)
);
CREATE TABLE element_no_id
(
  content         VARCHAR(100),
  LIST_PARENT_key BIGINT,
  LIST_PARENT     BIGINT
);

DROP TABLE IF EXISTS BYTE_ARRAY_OWNER;
CREATE TABLE BYTE_ARRAY_OWNER
(
  ID          BIGINT IDENTITY PRIMARY KEY,
  BINARY_DATA VARBINARY(20) NOT NULL
);

DROP TABLE IF EXISTS CHAIN4;
CREATE TABLE CHAIN4
(
  FOUR       BIGINT IDENTITY PRIMARY KEY,
  FOUR_VALUE VARCHAR(20)
);

DROP TABLE IF EXISTS CHAIN3;
CREATE TABLE CHAIN3
(
  THREE       BIGINT IDENTITY PRIMARY KEY,
  THREE_VALUE VARCHAR(20),
  CHAIN4      BIGINT,
  FOREIGN KEY (CHAIN4) REFERENCES CHAIN4 (FOUR)
);

DROP TABLE IF EXISTS CHAIN2;
CREATE TABLE CHAIN2
(
  TWO       BIGINT IDENTITY PRIMARY KEY,
  TWO_VALUE VARCHAR(20),
  CHAIN3    BIGINT,
  FOREIGN KEY (CHAIN3) REFERENCES CHAIN3 (THREE)
);

DROP TABLE IF EXISTS CHAIN1;
CREATE TABLE CHAIN1
(
  ONE       BIGINT IDENTITY PRIMARY KEY,
  ONE_VALUE VARCHAR(20),
  CHAIN2    BIGINT,
  FOREIGN KEY (CHAIN2) REFERENCES CHAIN2 (TWO)
);

DROP TABLE IF EXISTS CHAIN0;
CREATE TABLE CHAIN0
(
  ZERO       BIGINT IDENTITY PRIMARY KEY,
  ZERO_VALUE VARCHAR(20),
  CHAIN1     BIGINT,
  FOREIGN KEY (CHAIN1) REFERENCES CHAIN1 (ONE)
);