CREATE TABLE DummyEntity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ) PRIMARY KEY,
  name VARCHAR(128),
  created_By VARCHAR(128),
  created_Date TIMESTAMP,
  last_Modified_By VARCHAR(128),
  last_Modified_Date TIMESTAMP
);