CREATE TABLE aggregate_one
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ) PRIMARY KEY,
    NAME VARCHAR(100),
    two  INTEGER
);

CREATE TABLE REFERENCING_AGGREGATE
(
    ID   BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ) PRIMARY KEY,
    NAME VARCHAR(100),
    REF  INTEGER
);

CREATE TABLE employee
(
    organization    VARCHAR(20),
    employee_number BIGINT,
    name            VARCHAR(100),
    CONSTRAINT pk_employee PRIMARY KEY (employee_number, organization)
);

CREATE TABLE locker
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ) PRIMARY KEY,
    capacity        INTEGER,
    employee_number BIGINT,
    organization    VARCHAR(20),
    CONSTRAINT fk_locker_employee FOREIGN KEY (employee_number, organization)
        REFERENCES employee (employee_number, organization)
);
