DROP TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS_RELATION;
DROP TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS;

CREATE TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS (
    ID_TIMESTAMP TIMESTAMP PRIMARY KEY,
    BOOL CHAR(1),
    SOME_ENUM VARCHAR2(100),
    BIG_DECIMAL DECIMAL (38),
    BIG_INTEGER NUMBER(38, 0),
    "DATE" TIMESTAMP,
    LOCAL_DATE_TIME TIMESTAMP,
    ZONED_DATE_TIME VARCHAR2(30)
);

CREATE TABLE ENTITY_WITH_COLUMNS_REQUIRING_CONVERSIONS_RELATION (
    ID_TIMESTAMP TIMESTAMP PRIMARY KEY,
    DATA VARCHAR2(100)
);
