CREATE TABLE dummy_entity
(
    id_Prop          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME             VARCHAR(100),
    POINT_IN_TIME    TIMESTAMP(3),
    OFFSET_DATE_TIME TIMESTAMP(3),
    FLAG             BOOLEAN,
    REF              BIGINT
);

CREATE TABLE ENTITY_WITH_ZONED_DATE_TIME (ID BIGINT AUTO_INCREMENT PRIMARY KEY, CREATED_AT TIMESTAMP(3));
CREATE TABLE ENTITY_WITH_OFFSET_DATE_TIME (ID BIGINT AUTO_INCREMENT PRIMARY KEY, CREATED_AT TIMESTAMP(3));