DROP TABLE IF EXISTS dummy_entity;
DROP TABLE IF EXISTS ENTITY_WITH_ZONED_DATE_TIME;
DROP TABLE IF EXISTS ENTITY_WITH_OFFSET_DATE_TIME;

CREATE TABLE dummy_entity
(
    id_Prop          BIGINT IDENTITY PRIMARY KEY,
    NAME             VARCHAR(100),
    POINT_IN_TIME    DATETIME,
    OFFSET_DATE_TIME DATETIMEOFFSET,
    FLAG             BIT,
    REF              BIGINT
);

CREATE TABLE ENTITY_WITH_ZONED_DATE_TIME (id BIGINT IDENTITY PRIMARY KEY, CREATED_AT DATETIMEOFFSET);
CREATE TABLE ENTITY_WITH_OFFSET_DATE_TIME (id BIGINT IDENTITY PRIMARY KEY, CREATED_AT DATETIMEOFFSET);