DROP TABLE ReadOnlyIdEntity;
DROP TABLE PrimitiveIdEntity;
DROP TABLE ImmutableWithManualIdentity;
DROP TABLE ImmutableWithManualIdentity;
DROP TABLE SimpleSeq;
DROP SEQUENCE simple_seq_seq;
DROP TABLE PersistableSeq;
DROP SEQUENCE persistable_seq_seq;
DROP TABLE PrimitiveIdSeq;
DROP SEQUENCE "primitive_seq_seq";
DROP TABLE IdSeqWithVersion;
DROP SEQUENCE "seq_with_version_seq";

CREATE TABLE ReadOnlyIdEntity (
    ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100)
);

CREATE TABLE PrimitiveIdEntity (
    ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100)
);

CREATE TABLE ImmutableWithManualIdentity (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100)
);

CREATE TABLE SimpleSeq (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100)
);

CREATE SEQUENCE simple_seq_seq START WITH 1;

CREATE TABLE PersistableSeq (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100)
);

CREATE SEQUENCE persistable_seq_seq START WITH 1;

CREATE TABLE PrimitiveIdSeq (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100)
);

CREATE SEQUENCE "primitive_seq_seq" START WITH 1;

CREATE TABLE IdSeqWithVersion (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    VERSION NUMBER
);

CREATE SEQUENCE "seq_with_version_seq" START WITH 1;
