DROP TABLE ReadOnlyIdEntity;
DROP TABLE PrimitiveIdEntity;
DROP TABLE ImmutableWithManualIdentity;
DROP TABLE EntityWithSeq;
DROP TABLE PersistableEntityWithSeq;
DROP TABLE PrimitiveIdEntityWithSeq;

CREATE TABLE ReadOnlyIdEntity
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE PrimitiveIdEntity
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE ImmutableWithManualIdentity
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE SimpleSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE simple_seq_seq START WITH 1;
CREATE TABLE PersistableSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE persistable_seq_seq START WITH 1;
CREATE TABLE PrimitiveIdSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE primitive_seq_seq START WITH 1;
CREATE TABLE IdSeqWithVersion
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    VERSION BIGINT
);
CREATE SEQUENCE seq_with_version_seq START WITH 1;