DROP TABLE IF EXISTS ReadOnlyIdEntity;
DROP TABLE IF EXISTS PrimitiveIdEntity;
DROP TABLE IF EXISTS ImmutableWithManualIdentity;
DROP TABLE IF EXISTS EntityWithSeq;
DROP TABLE IF EXISTS SimpleSeq;
DROP SEQUENCE IF EXISTS simple_seq_seq;
DROP TABLE IF EXISTS PersistableSeq;
DROP SEQUENCE IF EXISTS persistable_seq_seq;
DROP TABLE IF EXISTS PrimitiveIdSeq;
DROP SEQUENCE IF EXISTS primitive_seq_seq;

CREATE TABLE ReadOnlyIdEntity
(
    ID   BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE PrimitiveIdEntity
(
    ID   BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE ImmutableWithManualIdentity
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE EntityWithSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE SimpleSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE simple_seq_seq START WITH 1;
CREATE TABLE PersistableSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE persistable_seq_seq START WITH 1;
CREATE TABLE PrimitiveIdSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE primitive_seq_seq START WITH 1;
CREATE TABLE IdSeqWithVersion
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    VERSION BIGINT
);
CREATE SEQUENCE seq_with_version_seq START WITH 1;
