DROP TABLE DUMMY_ENTITY/
DROP SEQUENCE DUMMY_ENTITY_SEQ/

CREATE TABLE DUMMY_ENTITY (id_Prop NUMBER(13,0), NAME VARCHAR(100))/
CREATE SEQUENCE DUMMY_ENTITY_SEQ/

ALTER TABLE DUMMY_ENTITY
  ADD (
    CONSTRAINT DUMMY_ENTITY_PK PRIMARY KEY (id_Prop)
  )/

CREATE OR REPLACE TRIGGER DUMMY_ENTITY_ON_INSERT
BEFORE INSERT ON DUMMY_ENTITY
  FOR EACH ROW
BEGIN
  SELECT DUMMY_ENTITY_SEQ.nextval
  INTO :new.id_Prop
  FROM dual;
END;/
