CREATE TABLE ENTITY_WITH_STRINGY_BIG_DECIMAL ( id IDENTITY PRIMARY KEY, Stringy_number DECIMAL(20,10));
CREATE TABLE OTHER_ENTITY ( ID IDENTITY PRIMARY KEY, CREATED DATE, ENTITY_WITH_STRINGY_BIG_DECIMAL INTEGER);
CREATE TABLE ENTITY_WITH_ZONED_DATE_TIME (ID BIGINT AUTO_INCREMENT PRIMARY KEY, CREATED_AT TIMESTAMP WITH TIME ZONE);
CREATE TABLE ENTITY_WITH_OFFSET_DATE_TIME (ID BIGINT AUTO_INCREMENT PRIMARY KEY, CREATED_AT TIMESTAMP WITH TIME ZONE);