DROP TABLE OTHER_ENTITY;
DROP TABLE ENTITY_WITH_STRINGY_BIG_DECIMAL;
DROP TABLE ENTITY_WITH_ZONED_DATE_TIME;
DROP TABLE ENTITY_WITH_OFFSET_DATE_TIME;

CREATE TABLE ENTITY_WITH_STRINGY_BIG_DECIMAL ( id BIGINT IDENTITY PRIMARY KEY, Stringy_number DECIMAL(20,10));
CREATE TABLE OTHER_ENTITY ( ID BIGINT IDENTITY PRIMARY KEY, CREATED DATE, ENTITY_WITH_STRINGY_BIG_DECIMAL INTEGER);
CREATE TABLE ENTITY_WITH_ZONED_DATE_TIME (id BIGINT IDENTITY PRIMARY KEY, CREATED_AT DATETIMEOFFSET);
CREATE TABLE ENTITY_WITH_OFFSET_DATE_TIME (id BIGINT IDENTITY PRIMARY KEY, CREATED_AT DATETIMEOFFSET);