DROP TABLE READONLYIDENTITY/
DROP SEQUENCE READONLYIDENTITY_SEQ/

CREATE TABLE READONLYIDENTITY (id NUMBER(20,0), NAME VARCHAR(100))/
CREATE SEQUENCE READONLYIDENTITY_SEQ/

ALTER TABLE READONLYIDENTITY
  ADD (
  CONSTRAINT READONLYIDENTITY_PK PRIMARY KEY (id)
  )/

CREATE OR REPLACE TRIGGER READONLYIDENTITY_ON_INSERT
BEFORE INSERT ON READONLYIDENTITY
FOR EACH ROW
BEGIN
SELECT READONLYIDENTITY_SEQ.nextval
       INTO :new.id
FROM dual;
END;/

DROP TABLE PRIMITIVEIDENTITY/
DROP SEQUENCE PRIMITIVEIDENTITY_SEQ/

CREATE TABLE PRIMITIVEIDENTITY (id NUMBER(20,0), NAME VARCHAR(100))/
CREATE SEQUENCE PRIMITIVEIDENTITY_SEQ/

ALTER TABLE PRIMITIVEIDENTITY
  ADD (
  CONSTRAINT PRIMITIVEIDENTITY_PK PRIMARY KEY (id)
  )/

CREATE OR REPLACE TRIGGER PRIMITIVEIDENTITY_ON_INSERT
BEFORE INSERT ON PRIMITIVEIDENTITY
FOR EACH ROW
BEGIN
SELECT PRIMITIVEIDENTITY_SEQ.nextval
       INTO :new.id
FROM dual;
END;/
