CREATE TABLE dummy_entity ( id BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(100));
CREATE TABLE element (id BIGINT AUTO_INCREMENT PRIMARY KEY, content VARCHAR(100), dummy_entity BIGINT);
CREATE TABLE collection_aggregate ( id BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(100));
CREATE TABLE collection_element (id BIGINT AUTO_INCREMENT PRIMARY KEY, content VARCHAR(100), collection_aggregate BIGINT);
