CREATE TABLE ReadOnlyIdEntity
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE PrimitiveIdEntity
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE ImmutableWithManualIdentity
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE SimpleSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE simple_seq_seq START WITH 1;
CREATE TABLE PersistableSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE persistable_seq_seq START WITH 1;
CREATE TABLE PrimitiveIdSeq
(
    ID   BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE SEQUENCE primitive_seq_seq START WITH 1;
CREATE TABLE IdSeqWithVersion
(
    ID      BIGINT NOT NULL PRIMARY KEY,
    NAME    VARCHAR(100),
    VERSION BIGINT
);
CREATE SEQUENCE seq_with_version_seq START WITH 1;
