CREATE TABLE dummy_entity
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEST VARCHAR(100)
);
CREATE TABLE dummy_entity2
(
    ID          BIGINT PRIMARY KEY,
    TEST        VARCHAR(100),
    PREFIX_ATTR BIGINT
);
