DROP TABLE dummy_entity;
DROP TABLE ENTITY_WITH_ZONED_DATE_TIME;
DROP TABLE ENTITY_WITH_OFFSET_DATE_TIME;

CREATE TABLE dummy_entity
(
    id_Prop          SERIAL PRIMARY KEY,
    NAME             VARCHAR(100),
    POINT_IN_TIME    TIMESTAMP,
    OFFSET_DATE_TIME TIMESTAMP WITH TIME ZONE,
    FLAG             BOOLEAN,
    REF              BIGINT
);
CREATE TABLE ENTITY_WITH_ZONED_DATE_TIME (id SERIAL PRIMARY KEY, CREATED_AT TIMESTAMPTZ);
CREATE TABLE ENTITY_WITH_OFFSET_DATE_TIME (id SERIAL PRIMARY KEY, CREATED_AT TIMESTAMPTZ);