DROP TABLE DUMMY_ENTITY/
DROP SEQUENCE DUMMY_ENTITY_SEQ/

CREATE TABLE DUMMY_ENTITY (id NUMBER(20,0), NAME VARCHAR(100))/
CREATE SEQUENCE DUMMY_ENTITY_SEQ/

ALTER TABLE DUMMY_ENTITY
  ADD (
  CONSTRAINT DUMMY_ENTITY_PK PRIMARY KEY (id)
  )/

CREATE OR REPLACE TRIGGER DUMMY_ENTITY_ON_INSERT
BEFORE INSERT ON DUMMY_ENTITY
FOR EACH ROW
BEGIN
SELECT DUMMY_ENTITY_SEQ.nextval
       INTO :new.id
FROM dual;
END;/


DROP TABLE ELEMENT/
DROP SEQUENCE ELEMENT_SEQ/

CREATE TABLE ELEMENT (id NUMBER(20,0), CONTENT VARCHAR(100), DUMMY_ENTITY_KEY VARCHAR(100), DUMMY_ENTITY NUMBER(20,0))/
CREATE SEQUENCE ELEMENT_SEQ/

ALTER TABLE ELEMENT
  ADD (
  CONSTRAINT ELEMENT_PK PRIMARY KEY (id)
  )/

CREATE OR REPLACE TRIGGER ELEMENT_ON_INSERT
BEFORE INSERT ON ELEMENT
FOR EACH ROW
BEGIN
SELECT ELEMENT_SEQ.nextval
       INTO :new.id
FROM dual;
END;/
