DROP TABLE DUMMY_ENTITY/
DROP SEQUENCE DUMMY_ENTITY_SEQ/

CREATE TABLE DUMMY_ENTITY (id NUMBER(13,0), NAME VARCHAR(100), DELETED CHAR(1), log NUMBER(20,0))/
CREATE SEQUENCE DUMMY_ENTITY_SEQ/

ALTER TABLE DUMMY_ENTITY
  ADD (
    CONSTRAINT DUMMY_ENTITY_PK PRIMARY KEY (id)
  )/

CREATE OR REPLACE TRIGGER DUMMY_ENTITY_ON_INSERT
BEFORE INSERT ON DUMMY_ENTITY
  FOR EACH ROW
BEGIN
  SELECT DUMMY_ENTITY_SEQ.nextval
  INTO :new.id
  FROM dual;
END;/



DROP TABLE log/
-- had to increase the precision for long
CREATE TABLE log ( id NUMBER(20,0), text VARCHAR(200))/
